Improve test-vm
Now building a slightly performant VM with SSH access.

diff --git a/test-vm b/test-vm
--- a/test-vm
+++ b/test-vm
@@ -1,18 +1,63 @@
 #!/bin/sh
 
 RUN=true
+ARGS=""
 
-case $1 in
-    build) RUN=;;
-esac
+while (( "$#" )); do
+    case "$1" in
+    -b|--build)
+        RUN=false
+        shift
+        ;;
+    -t|--trace)
+        ARGS="$ARGS --show-trace"
+        shift
+        ;;
+    -u|--update) # Update dependencies
+        if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+            nix flake lock --update-input $2
+            shift 2
+        else
+            echo "Error: Argument for $1 is missing" >&2
+            exit 1
+        fi
+        ;;
+    -s|--ssh) # SSH into the machine
+        SSH_IN=true
+        export QEMU_NET_OPTS=hostfwd=tcp::2221-:22
+        shift
+        ;;
+    --) # Forward all further arguments to nixos-rebuild
+        shift
+        ARGS="$ARGS $@"
+        break
+        ;;
+    -*|--*=|*) # unsupported flags
+        echo "Error: Unsupported flag or argument $1" >&2
+        exit 1
+        ;;
+    esac
+done
 
-rm ./nixos.qcow2
+alias build-vm="sudo nixos-rebuild --flake '.#test-vm' build-vm $ARGS"
 
-# TODO: set msize somehow
-# https://wiki.qemu.org/Documentation/9psetup#msize
-
-sudo nixos-rebuild --flake .#test-vm build-vm \
-&& if [ -n "$RUN" ]
+if build-vm 2>&1 | tee /tmp/test-vm-output && $RUN
 then
-    ./result/bin/run-nixos-vm
+    # Remove all files to remove state, asks for confirmation
+    rm -i ./*.qcow2
+
+    # Parse path to start VM
+    VM_CMD=$(cat /tmp/test-vm-output | tail -n 1 | awk 'END { print $NF}')
+
+    # Output diagnostic info
+    echo
+    echo "Running virtual machine: $VM_CMD"
+    $SSH_IN && echo "To connect via SSH use: ssh USER@localhost -p 2221" 
+    echo
+
+    # Run the VM
+    $VM_CMD
+
+    # Remove all files to remove state, asks for confirmation above 3 files
+    rm -I ./*.qcow2
 fi
